-- Phase N1: field templates for tactical board

alter table if exists public.tactics
  add column if not exists field_template_id bigint null,
  add column if not exists field_layout_mode text null;

create table if not exists public.field_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  description text null,
  full_horizontal_url text null,
  full_horizontal_path text null,
  full_horizontal_filename text null,
  full_vertical_url text null,
  full_vertical_path text null,
  full_vertical_filename text null,
  half_vertical_url text null,
  half_vertical_path text null,
  half_vertical_filename text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.field_templates enable row level security;

create or replace function public.set_updated_at_field_templates()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_field_templates_updated_at on public.field_templates;
create trigger trg_field_templates_updated_at
before update on public.field_templates
for each row execute function public.set_updated_at_field_templates();

create or replace function public.is_admin_user()
returns boolean
language sql
stable
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin' and coalesce(p.is_active, true) = true
  );
$$;

drop policy if exists "field_templates_read_authenticated" on public.field_templates;
create policy "field_templates_read_authenticated"
on public.field_templates
for select
using (auth.uid() is not null);

drop policy if exists "field_templates_admin_insert" on public.field_templates;
create policy "field_templates_admin_insert"
on public.field_templates
for insert
with check (public.is_admin_user());

drop policy if exists "field_templates_admin_update" on public.field_templates;
create policy "field_templates_admin_update"
on public.field_templates
for update
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists "field_templates_admin_delete" on public.field_templates;
create policy "field_templates_admin_delete"
on public.field_templates
for delete
using (public.is_admin_user());

alter table public.tactics
  drop constraint if exists tactics_field_template_id_fkey;

alter table public.tactics
  add constraint tactics_field_template_id_fkey
  foreign key (field_template_id)
  references public.field_templates(id)
  on delete set null;

insert into storage.buckets (id, name, public)
values ('field-templates', 'field-templates', true)
on conflict (id) do nothing;

drop policy if exists "field_templates_bucket_read" on storage.objects;
create policy "field_templates_bucket_read"
on storage.objects
for select
using (bucket_id = 'field-templates');

drop policy if exists "field_templates_bucket_admin_insert" on storage.objects;
create policy "field_templates_bucket_admin_insert"
on storage.objects
for insert
with check (bucket_id = 'field-templates' and public.is_admin_user());

drop policy if exists "field_templates_bucket_admin_update" on storage.objects;
create policy "field_templates_bucket_admin_update"
on storage.objects
for update
using (bucket_id = 'field-templates' and public.is_admin_user())
with check (bucket_id = 'field-templates' and public.is_admin_user());

drop policy if exists "field_templates_bucket_admin_delete" on storage.objects;
create policy "field_templates_bucket_admin_delete"
on storage.objects
for delete
using (bucket_id = 'field-templates' and public.is_admin_user());
