create extension if not exists pgcrypto with schema extensions;

create table if not exists public.password_reset_requests (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  email text not null,
  status text not null default 'pending' check (status in ('pending','handled','cancelled')),
  requested_at timestamptz not null default now(),
  handled_at timestamptz,
  handled_by_profile_id uuid references public.profiles(id) on delete set null
);

create index if not exists password_reset_requests_status_idx on public.password_reset_requests(status, requested_at desc);
create index if not exists password_reset_requests_email_idx on public.password_reset_requests(lower(email));

alter table public.password_reset_requests add column if not exists last_temp_password text;
alter table public.password_reset_requests add column if not exists email_subject text;
alter table public.password_reset_requests add column if not exists email_body text;

alter table public.password_reset_requests enable row level security;

drop policy if exists "Admins can read password reset requests" on public.password_reset_requests;
create policy "Admins can read password reset requests"
on public.password_reset_requests
for select to authenticated
using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

drop policy if exists "Admins can update password reset requests" on public.password_reset_requests;
create policy "Admins can update password reset requests"
on public.password_reset_requests
for update to authenticated
using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
)
with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create or replace function public.request_password_reset(p_email text)
returns public.password_reset_requests
language plpgsql
security definer
set search_path = public, extensions, auth
as $$
declare
  v_email text;
  v_profile public.profiles;
  v_request public.password_reset_requests;
begin
  v_email := lower(trim(coalesce(p_email, '')));
  if v_email = '' then
    raise exception 'Email requis';
  end if;

  select * into v_profile
  from public.profiles
  where lower(email) = v_email
  order by created_at desc nulls last
  limit 1;

  if not found then
    raise exception 'Aucun utilisateur trouvé avec cet email';
  end if;

  insert into public.password_reset_requests(profile_id, email, status)
  values (v_profile.id, v_email, 'pending')
  returning * into v_request;

  begin
    insert into public.notifications(profile_id, type, title, body, link_url)
    select p.id,
           'warning',
           'Demande de réinitialisation du mot de passe',
           coalesce(v_profile.full_name, v_profile.email, v_email) || ' a demandé une réinitialisation du mot de passe.',
           'users.html'
    from public.profiles p
    where p.role = 'admin';
  exception when undefined_table then
    null;
  end;

  return v_request;
end;
$$;

create or replace function public.admin_process_password_reset_request(p_request_id bigint)
returns table(
  request_id bigint,
  user_email text,
  temp_password text,
  email_subject text,
  email_body text
)
language plpgsql
security definer
set search_path = public, extensions, auth
as $$
declare
  caller_role text;
  req public.password_reset_requests;
  target_profile public.profiles;
  v_temp text;
  v_name text;
begin
  select role into caller_role from public.profiles where id = auth.uid();
  if caller_role <> 'admin' then
    raise exception 'Admin access required';
  end if;

  select * into req from public.password_reset_requests where id = p_request_id for update;
  if not found then
    raise exception 'Demande introuvable';
  end if;
  if req.status <> 'pending' then
    raise exception 'Cette demande a déjà été traitée';
  end if;

  select * into target_profile from public.profiles where id = req.profile_id;
  if not found then
    raise exception 'Utilisateur lié introuvable';
  end if;

  v_temp := substr(replace(gen_random_uuid()::text, '-', ''), 1, 10) || '!A';
  v_name := coalesce(nullif(trim(target_profile.full_name), ''), target_profile.email, req.email);

  update auth.users
  set encrypted_password = extensions.crypt(v_temp, extensions.gen_salt('bf')),
      updated_at = now(),
      recovery_token = '',
      email_change = '',
      email_change_token_new = ''
  where id = target_profile.id;

  if not found then
    raise exception 'Compte auth introuvable';
  end if;

  update public.password_reset_requests
  set status = 'handled',
      handled_at = now(),
      handled_by_profile_id = auth.uid(),
      last_temp_password = v_temp,
      email_subject = 'Réinitialisation de votre mot de passe TactiBoard',
      email_body = 'Bonjour ' || v_name || E'

Voici votre mot de passe temporaire : ' || v_temp || E'

Connectez-vous puis changez-le dès que possible.

Bien cordialement.'
  where id = req.id;

  return query
  select req.id,
         req.email,
         v_temp,
         'Réinitialisation de votre mot de passe TactiBoard',
         'Bonjour ' || v_name || E'

Voici votre mot de passe temporaire : ' || v_temp || E'

Connectez-vous puis changez-le dès que possible.

Bien cordialement.';
end;
$$;

grant execute on function public.request_password_reset(text) to anon, authenticated;
grant execute on function public.admin_process_password_reset_request(bigint) to authenticated;
