
create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  created_by_profile_id uuid not null references public.profiles(id) on delete cascade,
  assigned_admin_profile_id uuid references public.profiles(id) on delete set null,
  title text not null,
  description text not null,
  ticket_type text not null default 'support' check (ticket_type in ('bug','support','improvement','update')),
  priority text not null default 'medium' check (priority in ('low','medium','high','urgent')),
  status text not null default 'open' check (status in ('open','in_progress','waiting_user','resolved','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.support_ticket_comments (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.support_tickets(id) on delete cascade,
  author_profile_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_tickets_creator_idx on public.support_tickets(created_by_profile_id);
create index if not exists support_tickets_status_idx on public.support_tickets(status);
create index if not exists support_tickets_priority_idx on public.support_tickets(priority);
create index if not exists support_ticket_comments_ticket_idx on public.support_ticket_comments(ticket_id);

create or replace function public.set_support_tickets_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_support_tickets_updated_at on public.support_tickets;
create trigger trg_support_tickets_updated_at before update on public.support_tickets
for each row execute function public.set_support_tickets_updated_at();

create or replace function public.set_support_ticket_comments_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_support_ticket_comments_updated_at on public.support_ticket_comments;
create trigger trg_support_ticket_comments_updated_at before update on public.support_ticket_comments
for each row execute function public.set_support_ticket_comments_updated_at();

alter table public.support_tickets enable row level security;
alter table public.support_ticket_comments enable row level security;

drop policy if exists support_tickets_select_own_or_admin on public.support_tickets;
create policy support_tickets_select_own_or_admin
on public.support_tickets for select to authenticated
using (
  created_by_profile_id = auth.uid()
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

drop policy if exists support_tickets_insert_non_admin on public.support_tickets;
create policy support_tickets_insert_non_admin
on public.support_tickets for insert to authenticated
with check (
  created_by_profile_id = auth.uid()
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('coach','player'))
);

drop policy if exists support_tickets_update_admin on public.support_tickets;
create policy support_tickets_update_admin
on public.support_tickets for update to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

drop policy if exists support_ticket_comments_select_visible on public.support_ticket_comments;
create policy support_ticket_comments_select_visible
on public.support_ticket_comments for select to authenticated
using (
  exists (
    select 1 from public.support_tickets t
    where t.id = support_ticket_comments.ticket_id
      and (t.created_by_profile_id = auth.uid()
           or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  )
);

drop policy if exists support_ticket_comments_insert_visible on public.support_ticket_comments;
create policy support_ticket_comments_insert_visible
on public.support_ticket_comments for insert to authenticated
with check (
  author_profile_id = auth.uid()
  and exists (
    select 1 from public.support_tickets t
    where t.id = support_ticket_comments.ticket_id
      and (t.created_by_profile_id = auth.uid()
           or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  )
);
