
create table if not exists public.tactic_questions (
  id bigint generated by default as identity primary key,
  tactic_id bigint not null references public.tactics(id) on delete cascade,
  team_id bigint references public.teams(id) on delete cascade,
  player_profile_id uuid not null references public.profiles(id) on delete cascade,
  question_text text not null,
  answer_text text,
  answer_by_profile_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tactic_questions_tactic_idx on public.tactic_questions(tactic_id);
create index if not exists tactic_questions_player_idx on public.tactic_questions(player_profile_id);
create index if not exists tactic_questions_team_idx on public.tactic_questions(team_id);

create or replace function public.set_tactic_questions_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_tactic_questions_updated_at on public.tactic_questions;
create trigger trg_tactic_questions_updated_at
before update on public.tactic_questions
for each row execute function public.set_tactic_questions_updated_at();

alter table public.tactic_questions enable row level security;

drop policy if exists tactic_questions_select_player_own on public.tactic_questions;
create policy tactic_questions_select_player_own
on public.tactic_questions
for select to authenticated
using (player_profile_id = auth.uid());

drop policy if exists tactic_questions_insert_player_own on public.tactic_questions;
create policy tactic_questions_insert_player_own
on public.tactic_questions
for insert to authenticated
with check (player_profile_id = auth.uid());

drop policy if exists tactic_questions_select_staff_team on public.tactic_questions;
create policy tactic_questions_select_staff_team
on public.tactic_questions
for select to authenticated
using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  or exists (select 1 from public.coaches c where c.profile_id = auth.uid() and c.team_id = tactic_questions.team_id)
);

drop policy if exists tactic_questions_update_staff_team on public.tactic_questions;
create policy tactic_questions_update_staff_team
on public.tactic_questions
for update to authenticated
using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  or exists (select 1 from public.coaches c where c.profile_id = auth.uid() and c.team_id = tactic_questions.team_id)
)
with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  or exists (select 1 from public.coaches c where c.profile_id = auth.uid() and c.team_id = tactic_questions.team_id)
);
