
create table if not exists public.session_plans (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.sessions(id) on delete cascade,
  order_index integer not null default 1,
  title text not null,
  start_time time null,
  end_time time null,
  duration_minutes integer null,
  objective text null,
  instructions text null,
  equipment text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists session_plans_session_id_idx on public.session_plans(session_id, order_index);

create or replace function public.set_session_plans_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_session_plans_updated_at on public.session_plans;
create trigger trg_session_plans_updated_at
before update on public.session_plans
for each row execute function public.set_session_plans_updated_at();

alter table public.session_plans enable row level security;

drop policy if exists session_plans_select_authenticated on public.session_plans;
create policy session_plans_select_authenticated
on public.session_plans
for select
to authenticated
using (true);

drop policy if exists session_plans_insert_staff on public.session_plans;
create policy session_plans_insert_staff
on public.session_plans
for insert
to authenticated
with check (
  exists (
    select 1
    from public.sessions s
    left join public.coaches c on c.team_id = s.team_id and c.profile_id = auth.uid()
    where s.id = session_id
      and (
        exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
        or c.id is not null
      )
  )
);

drop policy if exists session_plans_update_staff on public.session_plans;
create policy session_plans_update_staff
on public.session_plans
for update
to authenticated
using (
  exists (
    select 1
    from public.sessions s
    left join public.coaches c on c.team_id = s.team_id and c.profile_id = auth.uid()
    where s.id = session_plans.session_id
      and (
        exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
        or c.id is not null
      )
  )
)
with check (
  exists (
    select 1
    from public.sessions s
    left join public.coaches c on c.team_id = s.team_id and c.profile_id = auth.uid()
    where s.id = session_id
      and (
        exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
        or c.id is not null
      )
  )
);

drop policy if exists session_plans_delete_staff on public.session_plans;
create policy session_plans_delete_staff
on public.session_plans
for delete
to authenticated
using (
  exists (
    select 1
    from public.sessions s
    left join public.coaches c on c.team_id = s.team_id and c.profile_id = auth.uid()
    where s.id = session_plans.session_id
      and (
        exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
        or c.id is not null
      )
  )
);
