-- Phase O1 - Live match stats for coach-managed team updates

alter table if exists public.matches
  add column if not exists live_status text not null default 'scheduled',
  add column if not exists live_period text not null default 'Q1',
  add column if not exists live_clock text not null default '15:00',
  add column if not exists stats_ready boolean not null default false,
  add column if not exists started_at timestamptz null,
  add column if not exists finished_at timestamptz null;

create table if not exists public.match_team_stats (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  points integer not null default 0,
  touchdowns integer not null default 0,
  xp_made integer not null default 0,
  two_pt_made integer not null default 0,
  field_goals_made integer not null default 0,
  first_downs integer not null default 0,
  total_yards integer not null default 0,
  passing_yards integer not null default 0,
  rushing_yards integer not null default 0,
  turnovers integer not null default 0,
  penalties integer not null default 0,
  third_down_made integer not null default 0,
  third_down_attempts integer not null default 0,
  red_zone_trips integer not null default 0,
  red_zone_tds integer not null default 0,
  possession_seconds integer not null default 0,
  updated_by_profile_id uuid null references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_match_team_stats unique (match_id, team_id)
);

create table if not exists public.match_events (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  event_type text not null,
  period text not null default 'Q1',
  clock_display text not null default '15:00',
  points_delta integer not null default 0,
  player_name text null,
  notes text null,
  created_by_profile_id uuid null references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_match_team_stats_match_team on public.match_team_stats(match_id, team_id);
create index if not exists idx_match_events_match_team on public.match_events(match_id, team_id, created_at desc);

create or replace function public.touch_updated_at_match_team_stats()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_match_team_stats_updated_at on public.match_team_stats;
create trigger trg_match_team_stats_updated_at
before update on public.match_team_stats
for each row execute function public.touch_updated_at_match_team_stats();

alter table if exists public.matches enable row level security;
alter table if exists public.match_team_stats enable row level security;
alter table if exists public.match_events enable row level security;

-- clean old policies if rerun
 drop policy if exists "matches_select_authenticated" on public.matches;
 drop policy if exists "matches_live_update_by_coach_team" on public.matches;
 drop policy if exists "match_team_stats_select_authenticated" on public.match_team_stats;
 drop policy if exists "match_team_stats_write_by_coach_team" on public.match_team_stats;
 drop policy if exists "match_events_select_authenticated" on public.match_events;
 drop policy if exists "match_events_write_by_coach_team" on public.match_events;

create policy "matches_select_authenticated"
on public.matches
for select
using (auth.role() = 'authenticated');

create policy "matches_live_update_by_coach_team"
on public.matches
for update
using (
  exists (
    select 1
    from public.coaches c
    where c.profile_id = auth.uid()
      and c.team_id = matches.team_id
  )
)
with check (
  exists (
    select 1
    from public.coaches c
    where c.profile_id = auth.uid()
      and c.team_id = matches.team_id
  )
);

create policy "match_team_stats_select_authenticated"
on public.match_team_stats
for select
using (auth.role() = 'authenticated');

create policy "match_team_stats_write_by_coach_team"
on public.match_team_stats
for all
using (
  exists (
    select 1
    from public.coaches c
    join public.matches m on m.id = match_team_stats.match_id
    where c.profile_id = auth.uid()
      and c.team_id = match_team_stats.team_id
      and m.team_id = c.team_id
  )
)
with check (
  exists (
    select 1
    from public.coaches c
    join public.matches m on m.id = match_team_stats.match_id
    where c.profile_id = auth.uid()
      and c.team_id = match_team_stats.team_id
      and m.team_id = c.team_id
  )
);

create policy "match_events_select_authenticated"
on public.match_events
for select
using (auth.role() = 'authenticated');

create policy "match_events_write_by_coach_team"
on public.match_events
for all
using (
  exists (
    select 1
    from public.coaches c
    join public.matches m on m.id = match_events.match_id
    where c.profile_id = auth.uid()
      and c.team_id = match_events.team_id
      and m.team_id = c.team_id
  )
)
with check (
  exists (
    select 1
    from public.coaches c
    join public.matches m on m.id = match_events.match_id
    where c.profile_id = auth.uid()
      and c.team_id = match_events.team_id
      and m.team_id = c.team_id
  )
);
